### ISSUE TITLE
Typo: swap fmt.Errorf with errors.New

### ISSUE THREAD

**Issue by dvrkps** [odeke-em/redtable#1]
https://github.com/odeke-em/redtable/blob/master/client.go#L25

**Comment by odeke-em** [comment]
Hello there @dvrkps, thank you for the issue.
So `fmt.Errorf` wraps `errors.New` directly https://golang.org/src/fmt/print.go?s=5673:5723#L201, am just too used to using `fmt.Errorf` :) of which the difference is in the invocation and extra string allocation in `fmt.Errorf`.
However to make it clearer and less redundant, please feel free to send a CL changing it to `errors.New`. Thank you.
